# Generated by Django 6.0 on 2026-01-08 08:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('lang_uz', models.BooleanField(default=True, verbose_name="O'zbek guruhi")),
                ('lang_ru', models.BooleanField(default=False, verbose_name='Rus guruhi')),
                ('lang_en', models.BooleanField(default=False, verbose_name='Ingliz guruhi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name="Yo'nalish kodi")),
                ('quota', models.PositiveIntegerField(verbose_name='Qabul kvotasi')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_language', models.CharField(choices=[('uz', 'Oze'), ('ru', 'Rus'), ('en', 'Eng')], default='uz', max_length=2)),
                ('first_name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiyasi')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Otchestvo')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jinsi')),
                ('passport_seria', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Pasport seriyasi AA1234567 formatida bo'lishi kerak", regex='^[A-Z]{2}\\d{7}$')], verbose_name='Pasport seriyasi')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Tel raqam formati: '+998901234567'.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message="To'g'ri email kiriting")], verbose_name='Elektron pochta')),
                ('address', models.TextField(verbose_name='Yashash manzili')),
                ('parent_first_name', models.CharField(max_length=50, verbose_name='Ota-onasining Ismi')),
                ('parent_last_name', models.CharField(max_length=50, verbose_name='Ota-onasining Familiyasi')),
                ('parent_phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Tel raqam formati: '+998901234567'.", regex='^\\+998\\d{9}$')], verbose_name='Ota-onasining Telefoni')),
                ('school_name', models.CharField(max_length=200, verbose_name='Tugatgan maktabi/kolleji')),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Maktabni tugatganmi?')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='MainApp.direction', verbose_name="Yo'nalish")),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1_score', models.FloatField(default=0, verbose_name='1-fan bali')),
                ('subject_2_score', models.FloatField(default=0, verbose_name='2-fan bali')),
                ('total_score', models.FloatField(default=0, verbose_name='Umumiy ball')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='MainApp.applicant')),
            ],
        ),
    ]
